### PR TITLE
Add additional setup information to README

### PR DESCRIPTION
**Pull request by andinus**
The build failed for me & was fixed after installing "karax" with
nimble.

### CODE REVIEW

**Comment by jyapayne** [comment]
This is an issue with nimble. I've had the issue many times but can never reproduce it when trying to.

Not a fan of having a pastebin in the readme, but I suppose it's fine as long as it's temporary. It might just be better to add a `Troubleshooting` section before the copyright with the note and a code block that has the full output. It's more eye catching and will either be easily seen if other people encounter it, or easily removed once it's been fixed

**Comment by dom96** [comment]
>  It might just be better to add a Troubleshooting section before the copyright with the note and a code block that has the full output. It's more eye catching and will either be easily seen if other people encounter it, or easily removed once it's been fixed

This.

**Comment by andinus** [comment]
Joey @ 2020-06-13 00:20 IST:

> Not a fan of having a pastebin in the readme, but I suppose it's fine
> as long as it's temporary. It might just be better to add a
> `Troubleshooting` section before the copyright with the note and a
> code block that has the full output. It's more eye catching and will
> either be easily seen if other people encounter it, or easily removed
> once it's been fixed

And also will appear in searches, I'll change this.

**Comment by dom96** [comment]
You can put a small excerpt of the paste into the readme, not whole thing.

**Comment by andinus** [comment]
Dominik Picheta @ 2020-06-13 00:52 IST:

> You can put a small excerpt of the paste into the readme, not whole thing.

Okay, I pushed the changes. Extra information was replaced with "[...]".

**Pull request merged**
