### PR TITLE
Replace webdriver with halonium

### PR DESCRIPTION
**Pull request by jyapayne**
I created a library called halonium that is the Nim version of s python selenium. It has the ability to use any of the web drivers and handles errors and thread management. I think it makes sense to use it here vs webdriver due to the current situation with Firefox having a bug in version 80 where clicks on popups don't register. 

Since halonium can work with any browser, if the tests don't work on one browser, we can run it on any other one.

### CODE REVIEW

**Comment by jyapayne** [comment]
Since these changes only affect testing, I'm going to merge them in without a review since they make testing possible again for me by using `createSession(Chrome)` because of geckodriver + Firefox's current issues.

**Comment by dom96** [comment]
Whoa, what, webdriver can also work with any browser (and from what I can see the support is definitely there for [even Chrome nowadays](https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md)). Furthermore, I specifically implemented it as it is the next thing which is getting adoption by all the major vendors: https://github.com/w3c/webdriver#vendor-status-documents.

I really wish you didn't just merge this without review. Quite frustrating to see from my perspective. Please do not do this sort of thing. I'm afraid that I will be reverting this. Replacing the library completely because of one bug is not the way to go.

**Comment by jyapayne** [comment]
I didn't mean to offend you and I apologize for merging without review, but I thought it would be okay since this doesn't affect anything besides tests. I won't do it again, but I would ask you to consider adding halonium because I wrote it to also follow the webdriver standard and I think having more options to run the tests is a good thing when issues like this pop up.

**Comment by dom96** [comment]
No harm done, I probably over-reacted to be fair.

But I'm still not sure what Halonium brings over the plain `webdriver`, browser support seems to be basically on par for both.

**Comment by jyapayne** [comment]
No worries. I overstepped a bit as well :)

True. Mainly halonium manages all of subprocess communication so you don't have to worry about it and also provides some of the convenience procs that I wrote for this repo `common.nim` file.

**Comment by jyapayne** [comment]
I was originally going to extend your webdriver project, but I figured the two projects had different goals. Yours is meant to be a lean interface and I wanted mine to be all inclusive.

**Pull request merged**
