### PR TITLE
Improvements to `Run`

### PR DESCRIPTION
**Pull request by stisa**
Based on feedback ( eg [here](https://forum.nim-lang.org/t/3276) ), here are some improvements for `run`:
- a blinking diamond to show it's doing something
- use `textContent` instead of `innerText` for better browser compatibility
- a button that opens the playground with the source already pasted in
- make it work in the post preview

Due to the loading indicator, the code is ~70 lines, but I don't think it's worth it to put it in a separate file.
Here's a gif:
blink

### CODE REVIEW

**Comment by dom96** [comment]
Could you also make it show up only for Nim code?

**Comment by stisa** [comment]
As far as I understand it, that's impossible to do in the forum itself, since the whole post is converted at once ([here I think?](https://github.com/nim-lang/nimforum/blob/master/forms.tmpl#L169)).
I'd need to change how the rst generator when doing `rstToHtml` treats code blocks, maybe by having it add a class with `lang-xxx` (eg `lang-nim`), and then I could restrict the js script to only target those elements that have the `lang-nim` class.

**Comment by dom96** [comment]
hrm, yeah, sadly it seems that indeed you'd need to touch the rst generator :\

**Comment by stisa** [comment]
The change in rstgen seems easy enough, I'd have to change [this line](https://github.com/nim-lang/Nim/blob/devel/lib/packages/docutils/rstgen.nim#L870) to
```nim
result = (d.config.getOrDefault"doc.listing_start" % [id, $params.lang],
```
and then in the forum `.cfg` file we'd need to add
```
doc.listing_start = "<pre class=\"listing $2\">"
```
After that it's just a matter of changing `document.getElementsByClassName("listing")` to 
`document.getElementsByClassName("langNim")`

Should I try making a pr to rstgen for this ?

**Comment by dom96** [comment]
> Should I try making a pr to rstgen for this ?

Go for it :)

**Comment by stisa** [comment]
Hey @dom96 , my pr to rstgen got merged some days ago and I already added the necessary changes to this one. 
If this pr gets merged the forum will likely need to depend on the next version of nim ( 0.18 I guess? )

**Comment by dom96** [comment]
Let's see how easy this will be to deploy... :)

**Comment by dom96** [comment]
Surprisingly easy. Thanks for the PRs and apologies for the delay :)

**Pull request merged**
