### PR TITLE
Allow to run nim code in posts (via playground)

### PR DESCRIPTION
**Pull request by stisa**
Javascript helper that adds a `Run` button to code listings, allowing to run them in `play.nim-lang.org`.

demo

### CODE REVIEW

**Comment by Yardanico** [comment]
@stisa nice one!

**Comment by dom96** [comment]
Nice. But could we make the Run button look a bit nicer? :)

**Comment by Bennyelg** [comment]
Jupyter ? 👍

**Comment by Yardanico** [comment]
@Bennyelg what do you mean by jupyter?

**Comment by stisa** [comment]
@dom96 sure, any suggestions? I'm not much of a designer.
Some possibilities, trying to keep the style of the buttons in the sidebar: btns

I personally like 3 and 4 the most.

**Comment by Yardanico** [comment]
@stisa I personally like 4 and 1 :)

**Comment by dom96** [comment]
Why don't you just reuse the style of the buttons in the sidebar?

**Comment by stisa** [comment]
I think I tried that but they use some trick with the alpha channel ([here](https://github.com/nim-lang/nimforum/blob/master/public/css/style.css#L444) ), I'll try again later today

**Comment by stisa** [comment]
Here is the button using the same css rules (except for removing button borders) as the links in the sidebar (left). Since the background color is ~black. it's basically invisible, so I also tried forcing the background color to be the same as the sidebar links (right)
btn
I still like 3 and 4 more ( maybe with pure white text instead of lightgray for 4 ), let me know which you prefer and I'll push it.

**Comment by dom96** [comment]
I prefer the right image. Nr. 4. looks like it's pressed in (and the contrast difference between the button and border is too much)

**Comment by stisa** [comment]
Done, I also inverted the border color change on hover  (`rgba(0, 0, 0, 0.5) -> rgba(255, 255, 255, 0.5)`) to make it more visible

**Pull request merged**
